# This is a basic workflow to test external links in .md files in the content directory

name: Gatsby_Test_Links

on:
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: self-hosted

    steps:

      - uses: actions/checkout@v2
      - uses: Kitura-Next/github-action-markdown-link-check@v2
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: 'mdlc_config.json'
          folder-path: 'content/'
          max-depth: -1
          check-modified-files-only: 'yes'
