# This is a basic workflow to build and test a Gatsby site

name: Gatsby_Test_Build

on:
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: build and test
        run: |
          echo "Starting Build!"
          sudo npm install -g gatsby-cli gh-pages
          cd website
          yarn install
          yarn test-build
          echo "Looking Good!"
